language: python
python: '3.8'
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
install: source devops/travis/install.sh
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python devops/travis/upload_artifacts.py
after_failure:
  - python devops/travis/upload_artifacts.py
