name: Build and test Arborize

on: [push]

jobs:
  build:
    name: test py${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install openmpi-bin libopenmpi-dev
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies & self
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Run tests & coverage
      run: |
        coverage run --parallel-mode -m unittest
        mpiexec -n 2 coverage run --parallel-mode -m unittest
        bash <(curl -s https://codecov.io/bash)